"""Exact Villain best-response analysis against a fully fixed Hero strategy."""

from .exact_response import (
    DEFAULT_MAX_PURE_STRATEGIES,
    BestResponseResult,
    StrategyEvaluation,
    count_villain_pure_strategies,
    enumerate_villain_pure_strategies,
    solve_exact_response,
)
from .candidates import HeroStrategyCandidate, generate_shift_candidates
from .comparison import (
    CandidateComparison,
    CandidateComparisonReport,
    compare_candidates,
)
from .analysis_report import (
    CandidateAnalysisReport,
    CandidateAnalysisRow,
    DeadlineConfiguration,
    SelectionConfiguration,
    SelectionSummaryCounts,
    build_candidate_analysis_report,
)
from .fixed_profile import FixedProfileValue, evaluate_fixed_profile
from .repeated import (
    DEFAULT_MAX_HORIZON,
    RESPONSE_MODE_BEST,
    RESPONSE_MODE_WORST,
    AdaptationDeadlineResult,
    AdaptationTimingRow,
    CandidateAdaptationDeadline,
    calculate_adaptation_deadline,
    calculate_candidate_adaptation_deadline,
    calculate_candidate_adaptation_deadlines,
)
from .selection import (
    L1_DISTANCE_EXCEEDS_LIMIT,
    NOT_ROBUSTLY_PROFITABLE,
    CandidateSelectionReport,
    ExcludedCandidate,
    candidate_exclusion_reasons,
    pareto_frontier,
    select_candidates,
    select_minimum_villain_ev,
)
from .game import (
    ChanceNode,
    GameTree,
    HeroNode,
    HeroStrategy,
    TerminalNode,
    VillainNode,
    VillainStrategy,
    collect_hero_info_sets,
    collect_villain_info_sets,
    iter_terminals,
    validate_hero_strategy,
    validate_tree,
    validate_villain_strategy,
)
from .payoffs import (
    CHOP,
    HERO,
    VILLAIN,
    compute_rake,
    make_fold_terminal,
    make_showdown_terminal,
)

__all__ = [
    "DEFAULT_MAX_PURE_STRATEGIES",
    "BestResponseResult",
    "StrategyEvaluation",
    "count_villain_pure_strategies",
    "enumerate_villain_pure_strategies",
    "solve_exact_response",
    "FixedProfileValue",
    "evaluate_fixed_profile",
    "HeroStrategyCandidate",
    "generate_shift_candidates",
    "CandidateComparison",
    "CandidateComparisonReport",
    "compare_candidates",
    "DEFAULT_MAX_HORIZON",
    "RESPONSE_MODE_BEST",
    "RESPONSE_MODE_WORST",
    "AdaptationDeadlineResult",
    "AdaptationTimingRow",
    "CandidateAdaptationDeadline",
    "calculate_adaptation_deadline",
    "calculate_candidate_adaptation_deadline",
    "calculate_candidate_adaptation_deadlines",
    "CandidateAnalysisReport",
    "CandidateAnalysisRow",
    "DeadlineConfiguration",
    "SelectionConfiguration",
    "SelectionSummaryCounts",
    "build_candidate_analysis_report",
    "L1_DISTANCE_EXCEEDS_LIMIT",
    "NOT_ROBUSTLY_PROFITABLE",
    "CandidateSelectionReport",
    "ExcludedCandidate",
    "candidate_exclusion_reasons",
    "pareto_frontier",
    "select_candidates",
    "select_minimum_villain_ev",
    "ChanceNode",
    "GameTree",
    "HeroNode",
    "HeroStrategy",
    "TerminalNode",
    "VillainNode",
    "VillainStrategy",
    "collect_hero_info_sets",
    "collect_villain_info_sets",
    "iter_terminals",
    "validate_hero_strategy",
    "validate_tree",
    "validate_villain_strategy",
    "CHOP",
    "HERO",
    "VILLAIN",
    "compute_rake",
    "make_fold_terminal",
    "make_showdown_terminal",
]
